/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package monoply.game;

public class playPanel extends javax.swing.JPanel {
    
    public static GamePanel gp;
    
    public static int playersNumber;
    /**
     * Creates new form playPanel
     */
    public playPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        playersNumberSpinner = new javax.swing.JSpinner();
        player1TextField = new javax.swing.JTextField();
        player2TextField = new javax.swing.JTextField();
        player3TextField = new javax.swing.JTextField();
        player4TextField = new javax.swing.JTextField();
        player5TextField = new javax.swing.JTextField();
        player6TextField = new javax.swing.JTextField();
        player7TextField = new javax.swing.JTextField();
        player8TextField = new javax.swing.JTextField();
        playersNumberLabel = new javax.swing.JLabel();
        playersNamesLabel = new javax.swing.JLabel();
        nextButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();

        playersNumberSpinner.setModel(new javax.swing.SpinnerNumberModel(8, 2, 8, 1));
        playersNumberSpinner.setToolTipText("");
        playersNumberSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                playersNumberSpinnerStateChanged(evt);
            }
        });

        player1TextField.setText("Player 1");

        player2TextField.setText("Player 2");

        player3TextField.setText("Player 3");

        player4TextField.setText("Player 4");

        player5TextField.setText("Player 5");

        player6TextField.setText("Player 6");

        player7TextField.setText("Player 7");

        player8TextField.setText("Player 8");

        playersNumberLabel.setText("Players Number");

        playersNamesLabel.setText("Players names");

        nextButton.setText("Next");
        nextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButtonActionPerformed(evt);
            }
        });

        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 346, Short.MAX_VALUE)
                .addComponent(nextButton, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(player3TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(116, 116, 116)
                        .addComponent(player4TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(player5TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(116, 116, 116)
                        .addComponent(player6TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(player7TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(116, 116, 116)
                        .addComponent(player8TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(playersNamesLabel)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(playersNumberLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(playersNumberSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(player1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(116, 116, 116)
                        .addComponent(player2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(playersNumberLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(playersNumberSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addComponent(playersNamesLabel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(player1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(player2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(player3TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(player4TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(player5TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(player6TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(player7TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(player8TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nextButton)
                    .addComponent(backButton))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void playersNumberSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_playersNumberSpinnerStateChanged
        int playersNumber = (Integer) playersNumberSpinner.getValue();
        switch (playersNumber) {
            case 2:
                player3TextField.setVisible(false);
                player4TextField.setVisible(false);
                player5TextField.setVisible(false);
                player6TextField.setVisible(false);
                player7TextField.setVisible(false);
                player8TextField.setVisible(false);
                break;
            case 3:
                player3TextField.setVisible(true);
                player4TextField.setVisible(false);
                player5TextField.setVisible(false);
                player6TextField.setVisible(false);
                player7TextField.setVisible(false);
                player8TextField.setVisible(false);
                break;
            case 4:
                player3TextField.setVisible(true);
                player4TextField.setVisible(true);
                player5TextField.setVisible(false);
                player6TextField.setVisible(false);
                player7TextField.setVisible(false);
                player8TextField.setVisible(false);
                break;
            case 5:
                player3TextField.setVisible(true);
                player4TextField.setVisible(true);
                player5TextField.setVisible(true);
                player6TextField.setVisible(false);
                player7TextField.setVisible(false);
                player8TextField.setVisible(false);
                break;
            case 6:
                player3TextField.setVisible(true);
                player4TextField.setVisible(true);
                player5TextField.setVisible(true);
                player6TextField.setVisible(true);
                player7TextField.setVisible(false);
                player8TextField.setVisible(false);
                break;
            case 7:
                player3TextField.setVisible(true);
                player4TextField.setVisible(true);
                player5TextField.setVisible(true);
                player6TextField.setVisible(true);
                player7TextField.setVisible(true);
                player8TextField.setVisible(false);
                break;
            case 8:
                player3TextField.setVisible(true);
                player4TextField.setVisible(true);
                player5TextField.setVisible(true);
                player6TextField.setVisible(true);
                player7TextField.setVisible(true);
                player8TextField.setVisible(true);
                break;

        }
    }//GEN-LAST:event_playersNumberSpinnerStateChanged

    private void nextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButtonActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        playersNumber = (Integer) playersNumberSpinner.getValue();
        gp = new GamePanel();
        mainFrame.mainPanel.add(gp);
        gp.setVisible(true);
        gp.playersInfo();
    }//GEN-LAST:event_nextButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        setVisible(false);
        mainFrame.sp.setVisible(true);
    }//GEN-LAST:event_backButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JButton nextButton;
    public static javax.swing.JTextField player1TextField;
    public static javax.swing.JTextField player2TextField;
    public static javax.swing.JTextField player3TextField;
    public static javax.swing.JTextField player4TextField;
    public static javax.swing.JTextField player5TextField;
    protected static javax.swing.JTextField player6TextField;
    public static javax.swing.JTextField player7TextField;
    public static javax.swing.JTextField player8TextField;
    private javax.swing.JLabel playersNamesLabel;
    private javax.swing.JLabel playersNumberLabel;
    public static javax.swing.JSpinner playersNumberSpinner;
    // End of variables declaration//GEN-END:variables
}
